Assignment/PresentationApp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using PresentationApp.Models;
using ShoppingCart.Application.Interfaces;
using ShoppingCart.Application.ViewModels;

namespace PresentationApp.Controllers
{
    public class ProductsController : Controller
    {
        private IProductsService _prodService;
        private ICategoriesService _categoriesService;
        private IWebHostEnvironment _webHostingEnviornment;
        public ProductsController(IProductsService prodService, ICategoriesService categoriesService, IWebHostEnvironment env)
        {
            _prodService = prodService;
            _categoriesService = categoriesService;
            _webHostingEnviornment = env;
        }
        public IActionResult Search(int category)
        {
            var list = _prodService.GetProductByCat(category);
            return View("Index", list);
        }
        /*public IActionResult AddToCart(Guid id)
        {

           // var list = _categoriesService.GetCategories();

            //CreateModel model = new CreateModel();

            //model.Categories = list.ToList();

            //return View(model);
        }*/
        public IActionResult Index()
        {
            try
            {
                var list = _prodService.GetProducts();
                return View(list);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [Authorize(Roles ="mgr")]
        public IActionResult Delete(Guid id)
        {
            _prodService.DeleteProduct(id);

            ViewData["feedback"] = "Product DELETED successfully"; // dont think li qed jehoda

            var list = _prodService.GetProducts();
            return RedirectToAction("Index",list);
        }

        public IActionResult Details (Guid id)
        {
            var p = _prodService.GetProduct(id);
            return View(p);
            //return View(_prodService.GetProduct(id));
        }

        [HttpGet]
        [Authorize(Roles ="mgr")]
        public IActionResult Create() //used to load the page with the empty textboxed to update the below method
        {
            var list = _categoriesService.GetCategories();

            CreateModel model = new CreateModel();
            
            model.Categories = list.ToList();

            return View(model);
        }
        
        [HttpPost]
        [Authorize(Roles ="mgr")]
        public IActionResult Create (CreateModel data) // this is triggered when the submit method is clicked
        {
            try
            {
                if (data.Product.Price != 0 && data.Product.Stock != 0 && data.Product.Name !=null)
                {
                    if (data.File != null)
                    {
                        if (data.File.Length > 0)
                        {
                            string newFileName = @"/images/" + Guid.NewGuid() + System.IO.Path.GetExtension(data.File.FileName);
                            string absPath = _webHostingEnviornment.WebRootPath;
                            using (var stream = System.IO.File.Create(absPath + newFileName))
                            {
                                data.File.CopyTo(stream);
                            }

                            data.Product.ImageURL = newFileName;
                        }
                    }

                    _prodService.AddProduct(data.Product);

                    ViewData["feedback"] = "Product added successfully";
                    ModelState.Clear(); //MHUX JEHODA #giveup
                }
            }
            catch (Exception ex)
            {
                ViewData["error"] = "Product was NOT ADDED. Please check your inputs";
            }

            var list = _categoriesService.GetCategories();
            data.Categories = list.ToList();
           
            return View(data);
        }
    }
}

Assignment/PresentationApp/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PresentationApp.Controllers
{
    public class SupportController : Controller
    {
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost] //recieve data from a form submission
        public ActionResult Contact(string email, string query)
        {

            if (string.IsNullOrEmpty(query))
            {
                ViewData["error"] = "One of the inputs is left empty";
            }
            else ViewData["feedback"] = "Thank you for your query. We will be with you shortly";

            return View();
        }
    }
}

Assignment/PresentationApp/Views/Shared/PartialFeedbackView.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@if (ViewData["feedback"] != null)
{
    <div class="alert alert-primary" role="alert">
        @ViewData["feedback"]
    </div>}

@if (ViewData["error"] != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewData["error"]
    </div>}

Assignment/PresentationApp/Views/Shared/SearchProductPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Assignment/PresentationApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PresentationApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PresentationApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Support" asp-action="Contact">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        @if (User.IsInRole("mgr"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Create">Create</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div style="margin-top :5px;">
                <partial>@Html.Partial("PartialFeedbackView")</partial>
            </div>

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PresentationApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>